### ISSUE TITLE
Compatibility with spring-data-rest

### ISSUE THREAD

**Issue by derjust** [derjust/spring-data-dynamodb#15]
> Migration of https://github.com/michaellavelle/spring-data-dynamodb/issues/57

**Comment by hmcmanus** [comment]
Great project. Vote +1 for this feature.

**Comment by fjvieira** [comment]
I managed a way of doing it. It is already deployed in a project I am working currently. I will put it in a pull request.

**Comment by gvasselai** [comment]
Hi @fjvieira , have you had a chance to submit the pull request? I'm also facing this problem with version 4.4.1.

**Comment by fjvieira** [comment]
Hey, @gvasselai , sorry to be late. 

I provided an example project with it.

You can check it on https://github.com/affinitas/DynamoDBExample

Regards.

**Comment by gauravbrills** [comment]
Thanks @fjvieira  you rock , that solved the issue with resolutions for post requests ,specially via the HAL browser .

**Comment by boothen** [comment]
The issue is because Spring Data Rest uses PersistentEntityResourceAssembler when rendering the resource. PersistentEntityResourceAssembler should use the DynamoDBMappingContext, however as this hasn't been constructed as a Spring Bean, it isn't picked up.

Simply declaring a DynamoDBMappingContext Spring Bean doesn't work either as it needs to be initialised. @fjvieira example project initialises DynamoDBMappingContext, however it means 2 separate instances of DynamoDBMappingContext are created.

If we expose the ability to inject a DynamoDBMappingContext bean into DynamoDBRepositoryConfigExtension we can avoid the initialisation code in the Application Configuration. Also, it'll mean a single instance of DynamoDBMappingContext will be used.

I've created a PR to allow the DynamoDBMappingContext to be declared as a Spring Bean and initialised correctly. 

https://github.com/derjust/spring-data-dynamodb/pull/168

If the PR is accepted, the Application Configuration for a Spring Data Rest service would be as follows:

```java
@Configuration
@EnableDynamoDBRepositories(basePackages = "com.acme.repositories", mappingContextRef = "dynamoDBMappingContext")
public class DynamoDBConfig {

	@Value("${amazon.dynamodb.endpoint}")
	private String amazonDynamoDBEndpoint;

	@Value("${amazon.aws.accesskey}")
	private String amazonAWSAccessKey;

	@Value("${amazon.aws.secretkey}")
	private String amazonAWSSecretKey;

	@Bean
	public AmazonDynamoDB amazonDynamoDB(AWSCredentials amazonAWSCredentials) {
		AmazonDynamoDB amazonDynamoDB = new AmazonDynamoDBClient(amazonAWSCredentials);

		if (StringUtils.isNotEmpty(amazonDynamoDBEndpoint)) {
			amazonDynamoDB.setEndpoint(amazonDynamoDBEndpoint);
		}
		return amazonDynamoDB;
	}

	@Bean
	public AWSCredentials amazonAWSCredentials() {
	    // Or use an AWSCredentialsProvider/AWSCredentialsProviderChain
		return new BasicAWSCredentials(amazonAWSAccessKey, amazonAWSSecretKey);
	}

        @Bean
        public DynamoDBMappingContext dynamoDBMappingContext() {
               return new DynamoDBMappingContext();
        }
}
```

**Comment by derjust** [comment]
Thanks to @boothen and his PR #168 this was merged into `master` and will be part of the upcoming `5.0.3` release.
Documentation to be found [here in the wiki](https://github.com/derjust/spring-data-dynamodb/wiki/Spring-Data-REST).
