### ISSUE TITLE
No field annotated with interface org.springframework.data.annotation.Id found!

### ISSUE THREAD

**Issue by derjust** [derjust/spring-data-dynamodb#24]
> Migration of https://github.com/michaellavelle/spring-data-dynamodb/issues/74

**Comment by rwhitsell** [comment]
A request for @derjust - can we rename this issue something like "No field annotated with interface org.springframework.data.annotation.Id found!" because it's likely other people have hit this problem but won't spot this issue because of the title.

The problem is that if you're using a hash key and a range key you have to design the entity class, and an "id" or primary key class, and do it in a particular way or you get this error message that doesn't really explain the problem. At first I presumed that spring-data-dynamodb simply doesn't support the hash and range keys together like you can with the AWS SDK. When I had a look at the sample code in the older repo, I found that there was an example. The entity and "id" class pattern is a bit odd, but it works.

To anyone seeing this error, make sure you're doing the following:

- You need a specialized class for your primary key. It needs to implement Serializable and will have the fields, getters, and setters for your hash key field and range key field.
- In your entity class, _instead of_ the hash key field and range key field, you have a field that is an instance of the specialized key class mentioned above. You must annotate that field with Spring's `@Id` annotation, but do not provide a getter or setter.
- Also in your entity class, do provide a getter and setter for your hash key field and range key field, _even though your entity doesn't have those fields_. You pass those through to the corresponding method on your primary key field.
- Make sure to lazy-create your primary key field in the hash key and range key setters in the entity.
- The hash key and range key getters in both your entity class and primary key class have to be annotated with `@DynamoDBHashKey` and `@DynamoDBRangeKey`, respectively. Yes, this is redundant.
- Make sure that your repo uses the primary key class for the "ID" class, otherwise you'll get another weird error about something not being an instance of the right class.

Do all of the above and the hash-key/range-ky combo will work properly. See the following two code examples, from the older spring-data-dynamodb repo, as a reference:

[Entity class](https://github.com/michaellavelle/spring-data-dynamodb-demo/blob/master/src/main/java/org/socialsignin/springframework/data/dynamodb/demo/domain/Reply.java)
[Entity id class](https://github.com/michaellavelle/spring-data-dynamodb-demo/blob/master/src/main/java/org/socialsignin/springframework/data/dynamodb/demo/domain/ReplyId.java)

**Comment by derjust** [comment]
Updated [wiki](https://github.com/derjust/spring-data-dynamodb/wiki/Use-Hash-Range-keys)
